
require_relative 'more_ruby/array.rb'
require_relative 'more_ruby/enumerable.rb'
require_relative 'more_ruby/falseclass.rb'
require_relative 'more_ruby/file.rb'
require_relative 'more_ruby/fixnum.rb'
require_relative 'more_ruby/float.rb'
require_relative 'more_ruby/hash.rb'
require_relative 'more_ruby/integer.rb'
require_relative 'more_ruby/nilclass.rb'
require_relative 'more_ruby/numeric.rb'
require_relative 'more_ruby/string.rb'
require_relative 'more_ruby/time.rb'
require_relative 'more_ruby/trueclass.rb'

